/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    campaigns: Campaign;
    posts: Post;
    payments: Payment;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      generateBrandedImage: TaskGenerateBrandedImage;
      generateBrandedVideo: TaskGenerateBrandedVideo;
      publishToPostiz: TaskPublishToPostiz;
      notifyMobileApp: TaskNotifyMobileApp;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'tenant_owner' | 'agent';
  tenants?: (number | Tenant)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-friendly ID (e.g., nairobi-west-agency)
   */
  slug: string;
  /**
   * The subdomain for this agency (e.g. "nebula" for nebula.smmhub.localhost). Use only lowercase letters, numbers, and hyphens.
   */
  subdomain: string;
  branding: {
    /**
     * Hex code for branding (e.g., #FF5733)
     */
    primaryColor: string;
    /**
     * Watermark logo for generated images/videos
     */
    logo?: (number | null) | Media;
  };
  billing: {
    plan?: ('starter' | 'pro' | 'agency') | null;
    /**
     * Remaining credits for branded video generation
     */
    credits?: number | null;
    /**
     * Maximum number of users/freelancers allowed for this tenant.
     */
    seatLimit: number;
    /**
     * Paybill or Till Number for this client
     */
    mpesaShortcode?: string | null;
    subscriptionStatus?: ('active' | 'past_due' | 'cancelled') | null;
    /**
     * Defines the value level and multiplier for this tenant.
     */
    serviceTier: 'self_service' | 'managed' | 'elite';
    /**
     * Advanced: Manual override for credit burn rate.
     */
    costMultiplier?: number | null;
  };
  integrations?: {
    /**
     * Automatically provisioned API Key for the dedicated Postiz Workspace
     */
    postizApiKey?: string | null;
    /**
     * Secret Key for external apps to push data to SMM Hub
     */
    ingestionKey?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * The agency that owns this asset
   */
  tenant?: (number | null) | Tenant;
  isPanorama?: boolean | null;
  panoramaType?: ('sphere' | 'cylinder') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  title: string;
  tenant: number | Tenant;
  status?: ('active' | 'paused' | 'draft' | 'completed') | null;
  scheduleMode: 'fixed' | 'evergreen';
  strategy?: ('cycle' | 'shuffle') | null;
  startDate: string;
  endDate?: string | null;
  automation?: {
    frequency?: ('manual' | 'daily' | 'weekly' | 'monthly') | null;
    timeOfDay?: string | null;
    dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  };
  resources: {
    /**
     * Total generation credits assigned to this specific campaign.
     */
    allocatedCredits: number;
    /**
     * Automatically calculated based on your schedule settings.
     */
    projectedUsage?: string | null;
  };
  nextRun?: string | null;
  lastRun?: string | null;
  defaultChannels?: ('facebook' | 'instagram' | 'linkedin' | 'twitter' | 'whatsapp_status')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Select the type of content to generate (Real Estate or Sports)
   */
  content: (
    | {
        /**
         * Flexible JSON data: { price, location, features: [], agent: {} }
         */
        data:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'real-estate-listing';
      }
    | {
        /**
         * Flexible JSON data: { matches: [], league, predictions, slipCode }
         */
        data:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'sports-fixture';
      }
    | {
        /**
         * Flexible JSON data: { price, salePrice, productName, stockStatus: "in_stock" | "sold_out", sku }
         */
        data:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'retail-product';
      }
    | {
        /**
         * Flexible JSON data: { price, duration, inclusions: [], serviceCode, availability: "available" | "booked" }
         */
        data:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'service-package';
      }
  )[];
  tenant?: (number | null) | Tenant;
  /**
   * Link this post to a specific Campaign or Content Library.
   */
  campaign?: (number | null) | Campaign;
  usageStats?: {
    usageCount?: number | null;
    lastUsedAt?: string | null;
  };
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  channels?: ('facebook' | 'instagram' | 'linkedin' | 'twitter' | 'whatsapp_status')[] | null;
  scheduledAt?: string | null;
  /**
   * Auto-repost this content periodically (e.g. Vacant Listings)
   */
  recurrenceInterval?: ('none' | 'daily' | 'weekly' | 'monthly') | null;
  distributionStatus?: ('pending' | 'queued' | 'published' | 'recurring' | 'failed') | null;
  distributionLogs?:
    | {
        timestamp?: string | null;
        status?: string | null;
        destination?: string | null;
        id?: string | null;
      }[]
    | null;
  assets?: {
    rawMedia?: (number | null) | Media;
    /**
     * This is auto-generated by the Creative Engine
     */
    brandedMedia?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  tenant: number | Tenant;
  amount: number;
  /**
   * Format: 2547XXXXXXXX
   */
  phoneNumber: string;
  transactionId?: string | null;
  checkoutRequestId: string;
  status?: ('pending' | 'completed' | 'failed') | null;
  rawCallback?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateBrandedImage' | 'generateBrandedVideo' | 'publishToPostiz' | 'notifyMobileApp';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'generateBrandedImage' | 'generateBrandedVideo' | 'publishToPostiz' | 'notifyMobileApp')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  isPanorama?: T;
  panoramaType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  subdomain?: T;
  branding?:
    | T
    | {
        primaryColor?: T;
        logo?: T;
      };
  billing?:
    | T
    | {
        plan?: T;
        credits?: T;
        seatLimit?: T;
        mpesaShortcode?: T;
        subscriptionStatus?: T;
        serviceTier?: T;
        costMultiplier?: T;
      };
  integrations?:
    | T
    | {
        postizApiKey?: T;
        ingestionKey?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  tenant?: T;
  status?: T;
  scheduleMode?: T;
  strategy?: T;
  startDate?: T;
  endDate?: T;
  automation?:
    | T
    | {
        frequency?: T;
        timeOfDay?: T;
        dayOfWeek?: T;
      };
  resources?:
    | T
    | {
        allocatedCredits?: T;
        projectedUsage?: T;
      };
  nextRun?: T;
  lastRun?: T;
  defaultChannels?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        'real-estate-listing'?:
          | T
          | {
              data?: T;
              id?: T;
              blockName?: T;
            };
        'sports-fixture'?:
          | T
          | {
              data?: T;
              id?: T;
              blockName?: T;
            };
        'retail-product'?:
          | T
          | {
              data?: T;
              id?: T;
              blockName?: T;
            };
        'service-package'?:
          | T
          | {
              data?: T;
              id?: T;
              blockName?: T;
            };
      };
  tenant?: T;
  campaign?: T;
  usageStats?:
    | T
    | {
        usageCount?: T;
        lastUsedAt?: T;
      };
  caption?: T;
  channels?: T;
  scheduledAt?: T;
  recurrenceInterval?: T;
  distributionStatus?: T;
  distributionLogs?:
    | T
    | {
        timestamp?: T;
        status?: T;
        destination?: T;
        id?: T;
      };
  assets?:
    | T
    | {
        rawMedia?: T;
        brandedMedia?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenant?: T;
  amount?: T;
  phoneNumber?: T;
  transactionId?: T;
  checkoutRequestId?: T;
  status?: T;
  rawCallback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateBrandedImage".
 */
export interface TaskGenerateBrandedImage {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateBrandedVideo".
 */
export interface TaskGenerateBrandedVideo {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPublishToPostiz".
 */
export interface TaskPublishToPostiz {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNotifyMobileApp".
 */
export interface TaskNotifyMobileApp {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}