import { CollectionConfig } from 'payload'

export const Posts: CollectionConfig = {
  slug: 'posts',
  admin: {
    useAsTitle: 'title',
    group: 'Marketing',
  },
  access: {
    read: () => true,
  },
  hooks: {
    afterChange: [
      async ({ doc, operation, req, previousDoc }) => {
        // 1. Creative Engine Trigger (New Raw Media)
        if (doc.assets?.rawMedia && !doc.assets?.brandedMedia) {
          const rawMedia = await req.payload.findByID({
            collection: 'media',
            id: doc.assets.rawMedia,
          })
          const isVideo = rawMedia.mimeType?.startsWith('video/')
          const taskSlug = isVideo ? 'generateBrandedVideo' : 'generateBrandedImage'

          await req.payload.jobs.queue({
            task: taskSlug,
            input: {
              postId: doc.id,
              mediaId: doc.assets.rawMedia,
              price: doc.price || 'Contact for Price',
              title: doc.title || 'Property for Sale',
              tenantId: doc.tenant,
            },
          })
        }

        // 2. Distribution Trigger
        // If status changes to "Queued" AND we have branded media, send it!
        // (In a real app, a Cron Job might pick this up instead, but this is an instant trigger for demo)
        if (
          doc.distributionStatus === 'queued' && 
          previousDoc?.distributionStatus !== 'queued' &&
          doc.assets?.brandedMedia
        ) {
          await req.payload.jobs.queue({
            task: 'publishToPostiz',
            input: {
              postId: doc.id,
              channels: doc.channels || [],
            },
          })
        }
      },
    ],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      admin: {
        description: 'Heading for the branded graphic',
      },
    },
    {
      name: 'price',
      type: 'text',
      required: true,
      admin: {
        description: 'Price display (e.g. KES 5,000,000)',
      },
    },
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
    },
    {
      name: 'campaign',
      type: 'relationship',
      relationTo: 'campaigns',
      required: true,
    },
    {
      name: 'caption',
      type: 'richText',
      label: 'Post Caption',
    },
    {
      name: 'channels',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Facebook Page', value: 'facebook' },
        { label: 'Instagram Feed', value: 'instagram' },
        { label: 'LinkedIn', value: 'linkedin' },
        { label: 'X (Twitter)', value: 'twitter' },
        { label: 'WhatsApp Status (Manual)', value: 'whatsapp_status' },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'scheduledAt',
          type: 'date',
          admin: {
            position: 'sidebar',
          },
        },
        {
          name: 'distributionStatus',
          type: 'select',
          defaultValue: 'pending',
          options: [
            { label: 'Pending Approval', value: 'pending' },
            { label: 'Queued', value: 'queued' },
            { label: 'Published', value: 'published' },
            { label: 'Failed', value: 'failed' },
          ],
          admin: {
            position: 'sidebar',
          },
        },
      ],
    },
    {
      name: 'assets',
      type: 'group',
      label: 'Creative Assets',
      fields: [
        {
          name: 'rawMedia',
          type: 'relationship',
          relationTo: 'media',
          label: 'Raw Input (User Upload)',
        },
        {
          name: 'brandedMedia',
          type: 'relationship',
          relationTo: 'media',
          label: 'Final Output (Generated)',
          admin: {
            readOnly: true,
            description: 'This is auto-generated by the Creative Engine',
          },
        },
      ],
    },
  ],
}
