import { CollectionConfig } from 'payload'
import { RealEstateListing, SportsFixture } from '../blocks/CreativeBlocks'

export const Posts: CollectionConfig = {
  slug: 'posts',
  admin: {
    useAsTitle: 'title',
    group: 'Marketing',
  },
  access: {
    read: () => true,
  },
  hooks: {
    afterChange: [
      async ({ doc, operation, req, previousDoc }) => {
        // 1. Creative Engine Trigger (New Raw Media)
        if (doc.assets?.rawMedia && !doc.assets?.brandedMedia) {
          const rawMediaId = typeof doc.assets.rawMedia === 'object' ? doc.assets.rawMedia.id : doc.assets.rawMedia
          const rawMedia = await req.payload.findByID({
            collection: 'media',
            id: rawMediaId,
          })
          const isVideo = rawMedia.mimeType?.startsWith('video/')
          const taskSlug = isVideo ? 'generateBrandedVideo' : 'generateBrandedImage'

          // Extract Data from the first Content Block
          const activeBlock = doc.content?.[0]
          let creativeData = {}

          if (activeBlock) {
             creativeData = {
               template: activeBlock.blockType,
               ...activeBlock
             }
          }

          await req.payload.jobs.queue({
            task: taskSlug,
            input: {
              postId: doc.id,
              mediaId: doc.assets.rawMedia,
              tenantId: doc.tenant,
              data: creativeData,
            },
          })
        }

        // 2. Distribution Trigger
        if (
          doc.distributionStatus === 'queued' && 
          previousDoc?.distributionStatus !== 'queued' &&
          (doc.assets?.brandedMedia || (typeof doc.assets?.brandedMedia === 'object' && doc.assets.brandedMedia !== null))
        ) {
          await req.payload.jobs.queue({
            task: 'publishToPostiz',
            input: {
              postId: doc.id,
              channels: doc.channels || [],
            },
          })
        }
      },
    ],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      label: 'Internal Title (Admin Only)',
    },
    {
      name: 'content',
      type: 'blocks',
      required: true,
      minRows: 1,
      maxRows: 1,
      blocks: [
        RealEstateListing,
        SportsFixture,
      ],
      admin: {
        description: 'Select the type of content to generate (Real Estate or Sports)',
      },
    },
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
    },
    {
      name: 'campaign',
      type: 'relationship',
      relationTo: 'campaigns',
      required: true,
    },
    {
      name: 'caption',
      type: 'richText',
      label: 'Post Caption',
    },
    {
      name: 'channels',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Facebook Page', value: 'facebook' },
        { label: 'Instagram Feed', value: 'instagram' },
        { label: 'LinkedIn', value: 'linkedin' },
        { label: 'X (Twitter)', value: 'twitter' },
        { label: 'WhatsApp Status (Manual)', value: 'whatsapp_status' },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'scheduledAt',
          type: 'date',
          admin: {
            position: 'sidebar',
          },
        },
        {
          name: 'distributionStatus',
          type: 'select',
          defaultValue: 'pending',
          options: [
            { label: 'Pending Approval', value: 'pending' },
            { label: 'Queued', value: 'queued' },
            { label: 'Published', value: 'published' },
            { label: 'Failed', value: 'failed' },
          ],
          admin: {
            position: 'sidebar',
          },
        },
      ],
    },
    {
      name: 'assets',
      type: 'group',
      label: 'Creative Assets',
      fields: [
        {
          name: 'rawMedia',
          type: 'relationship',
          relationTo: 'media',
          label: 'Raw Input (User Upload)',
        },
        {
          name: 'brandedMedia',
          type: 'relationship',
          relationTo: 'media',
          label: 'Final Output (Generated)',
          admin: {
            readOnly: true,
            description: 'This is auto-generated by the Creative Engine',
          },
        },
      ],
    },
  ],
}
